import React from 'react';
import Layout from '../components/Layout';
import SEO from '../components/SEO';

const Terms = () => {
    return (
        <Layout>
            <SEO title="Terms of Service" description="Terms of service and usage guidelines for the Gov Notice Decoder." />
            <div className="max-w-4xl mx-auto text-slate-300 p-8">
                <h1 className="text-3xl font-bold text-white mb-6">Terms of Service</h1>
                <div className="space-y-4">
                    <section>
                        <h2 className="text-xl font-semibold text-white mb-2">1. Acceptance of Terms</h2>
                        <p>By accessing and using this tool, you accept and agree to be bound by the terms and provision of this agreement.</p>
                    </section>

                    <section className="bg-red-900/20 border border-red-500/50 p-4 rounded-lg my-6">
                        <h2 className="text-xl font-semibold text-red-200 mb-2">Critical Disclaimer</h2>
                        <p className="font-medium text-red-100">
                            This tool must not be used to replace professional advice. The analysis provided is generated by AI and may contain errors. Always consult a qualified legal professional for official government notices.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-xl font-semibold text-white mb-2">2. No Legal Advice</h2>
                        <p>The content provided by this application is for informational purposes only and does not constitute legal advice.</p>
                    </section>

                    <section>
                        <h2 className="text-xl font-semibold text-white mb-2">3. Limitation of Liability</h2>
                        <p>We shall not be liable for any direct, indirect, incidental, special, consequential or exemplary damages resulting from the use of this tool.</p>
                    </section>
                </div>
            </div>
        </Layout>
    );
};

export default Terms;
